### ISSUE TITLE
Leds are dark (but not completely black)

### ISSUE THREAD

**Issue by guinaldi** [fabsenet/adrilight#5]
Hello!

First of all, i would like to thank you for this amazing job! For me, it's the best app for ambilight projects!
But i'm having some problems. I think the leds are too low bright. Brightness is set to 255 in .ino and still getting low light =/.

Saturation is 0 too.
On full color (red 255 or blue 255 or green 255) its ok. The problem is with mixed colors.

What should i do to improve this?

Thank you for your time and effort!
Hugs from Brazil!

**Comment by fabsenet** [comment]
Okay,

we need to devide and conquer here.

Could you please power the arduino via an usb charger? it should go into "demo mode" where all colors are walking around. (there should be no connection to the pc)

Are these colors as bright as you think they should be? If not, your leds may check your power requirements and power cabling otherwise report back please.

**Comment by guinaldi** [comment]
Yes.

Tested it forcing native colors on the stripe via usb too. My stripe is powered with a 12V power suply (My leds are 12v) and its ok.
Rainbow mode its really bright. That's why I openned this question... Rainbow its ok... The problem is that the color that is getting from the monitor is way darker then the screen in such cases.
Brown and colors with mixed rbg's with not that low bright, its veryyy low bright... lol.
But with full red, full blue and full green its perfect.
Maybe some control brightness on app should help. But i don't know how to implement this on this project.
I'm using Windows 10 btw.

Thank you.

**Comment by fabsenet** [comment]
okay,

this problem is really hard to "debug" from the distance.

Just one obvious question: did you disable the overlay because it influences the detected colors. (the software detects its own black overlay...). anyway i cannot make up a way why this should behave differently with different colors ?!

if this is not the case, please provide:
- a screenshot of the adrilight window with your settings
- some photos of your installed leds and power supply and arduino connections
- a video from the screen with the leds running when you play [this test video](https://www.youtube.com/watch?v=DVvpPhY-a5Y) you could share your video on youtube again and privide a link here

I hope some of the stuff above will yield some more insights. otherwise i would need to accelerate my plans on providing some debug output within the program because you may be one of the first with problems but most probably not the last.

We will sort this out but it might take some time and effort for you and me

**Comment by guinaldi** [comment]
I don't think its a problem because its showing perfect the leds.
Just a perception and we could find a way to set a boost on brightness on the identified color from the screen... Just a tought but i have no idea how and where to implement this.
 
My stripe isn't finished soldered. I'm using protoboard to connect this.
But in rainbow mode its showing really nice colors.

Could be the wires?

**Comment by fabsenet** [comment]
So,

I made a new release: https://github.com/fabsenet/adrilight/releases/tag/v0.1.2-alpha

Please use this one and change the lightning mode to *linear lighting*.

Non-linear lighting is the default and the earlier versions only had non-linear lighting.

In linear lighting mode the color values for RGB are send to the arduiono and from there to the led strip *as is*. 
In *non* linear mode, the detected RGB values are modified to account for proper PWM dimming where the perceived color of the LED is kind of linear for the human eye but the actual brightness values sent to the LED are not. I am suspecting you have an led strip with chips on it, which account for this on their own and therefor the non linear mathematics were applied twice.

the linear mode on my personal setup does emphasize light over color and is mostly white or black. The non linear mode has (at least in my setup) colors which match the screen colors quite accurate.

Here is a comparison on my setup:
![linear_vs_non_linear_by_example](https://cloud.githubusercontent.com/assets/2065705/20685521/0d3ace6e-b5b5-11e6-9540-909618de439d.jpg)

**Comment by guinaldi** [comment]
Ok! 
I will try this version and post here the results.

Thank you!

**Comment by guinaldi** [comment]
Linear

![img_20161130_233503063_hdr](https://cloud.githubusercontent.com/assets/10552043/20778628/216fc3ce-b756-11e6-98f2-e3b7fc6c6314.jpg)

Non-Linear
![img_20161130_233443427_hdr](https://cloud.githubusercontent.com/assets/10552043/20778629/2174b276-b756-11e6-82e3-59ec8bc41d22.jpg)


Gorgeous!!
Thank you a lot!!
