### ISSUE TITLE
adrilight configure with enigmalight

### ISSUE THREAD

**Issue by rebdel** [fabsenet/adrilight#6]
Hello Fabian,

which kind of hardware can i compare adrilight?
Atmoli/sedu/boblight?
I want to configure it with my enigma receiver and it won´t work 

BR
Frank

**Comment by fabsenet** [comment]
I do not know any of the 3 you named so chances are, nothing will work. 

can you please lay out your hardware configuration (what box/boxes?, what is connected to what?)?
Can you tell me what you want to archive(ambilight from the box/ambilight from other video sources/...)?

thing is, i am pretty sure, it will not work, because the software on the pc speaks a custom data protocol to the arduino. but if i get details, there might be still something i can do to make it work, but I need more details.
