### ISSUE TITLE
Working but randomly flashing

### ISSUE THREAD

**Issue by psbeau** [fabsenet/adrilight#67]
I have the same problem on two different systems. Everything works but I'm getting constant random flashes while sending colour information. It doesn't flash while sending random colours.  Rebooting doesnt help and I can see the preview.

It can't be a power issue, as I have a 20A power supply on my desktop setup, feeding power to both ends, with the controller 5v disconnected from the LEDs. The controllers I'm using are genuine Lolin D1 minis.
System 1 has 414 LEDs and is set up as such in the .ino file, the Adrilight software 2.06 is set up 137H - 72V
System 2 has 120 LEDs and is set up as such in the .ino file, the Adrilight software 2.06 is set up 40H - 22V

This system is amazing but I just wish it would work.

**Comment by fabsenet** [comment]
It is the esp8266 in the d1 mini. I made a video some weeks ago trying it
out and having the same flashing. https://youtu.be/rFHU1WkLQHU it is in
German so ymmv. It related down to missing timers and the hard requirements
for accurate timing for the ws2812.

Switch to an arduino Uno or bigger. One of your installations is very
large, it might not work because of limited ram. You may try to compile for
a given arduino with your led numbers entered before actually ordering a
real device.

I plan to make a follow up using an esp32. If it works, I want to maybe
switch to wifi as the transport. I already have the esp32 here but I cannot
commit to a relyable time frame, sorry. The esp32 may work significantly
better because it has two cores but I can only tell it really after trying.

So try an arduino or wait a little and try the esp32 but your esp8266 (as
well as my own ones) are useless for adrilight, as far as I know, sorry.

AbsenteeAtom <notifications@github.com> schrieb am Mo., 15. Okt. 2018,
23:35:

**Comment by psbeau** [comment]
Thanks fabsenet, I'll try a different controller and report back.

**Comment by psbeau** [comment]
The Arduino Uno worked perfectly on the small system but was 800 bytes short of memory for the 414 LED setup. I wondered if the D1 mini pro was any better but was unable to get anything out of that on first try. I'll keep trying until my ESP32-WROOM-32D arrives.

**Comment by psbeau** [comment]
Hi Fabsenet, I now have an ESP32-DevKitC V4 development board. I have connected and uploaded adrilight.ino using pin 12 for data. It loads without errors after installing the Arduino core and selecting ESP32 dev module. Initially, the 120 LEDs light but with a rainbow pattern and heartbeat pulse, when I turn on Enable Sending, the pulse stops and I'm left with the static rainbow pattern, so it seems to be responding to pin 12.
Any tips as to how I can progress? Thanks
